name = "upi-easy-api"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
JWT_EXPIRY = "15m"
REFRESH_TOKEN_EXPIRY = "30d"
GOOGLE_WEB_CLIENT_ID = "332345540842-ks8bq4csr4lklkvv3tesgkig2b221m23.apps.googleusercontent.com"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[[d1_databases]]
binding = "upi_easy_db"
database_name = "upi-easy-db"
database_id = "6daf6ea6-2c17-4f6d-8d6f-a129f1c69716"